In [23]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import statsmodels.api as sm

In [2]:
data= pd.read_csv('Self Awareness Dataset.csv')
data

Date       Day  Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  \
0   14-Jan    Friday           7              2           2             0   
1   15-Jan  Saturday           7              2           0             0   
2   16-Jan    Sunday           7              0           4             0   
3   17-Jan    Monday           8              4           2             0   
4   18-Jan   Tuesday           8              2           1             0   
..     ...       ...         ...            ...         ...           ...   
62  17-Mar  Thursday           8              0           0             0   
63  18-Mar    Friday           8              2           2             0   
64  19-Mar  Saturday           7              2           0             0   
65  20-Mar    Sunday           7              2           0             0   
66  21-Mar    Monday           8              2           0             0   

    Work Hour  End of the day Feeling (0 to 10)  Unnamed: 8  Unnamed: 9  \
0           0                                 1         NaN         NaN   
1           0                                 2         NaN         NaN   
2           0                                 1         NaN         NaN   
3           0                                 1         NaN         NaN   
4           0                                 1         NaN         NaN   
..        ...                               ...         ...         ...   
62          2                                 2         NaN         NaN   
63          1                                 1         NaN         NaN   
64          2                                 2         NaN         NaN   
65          0                                 0         NaN         NaN   
66          0                                 0         NaN         NaN   

    Unnamed: 10  
0           NaN  
1           NaN  
2           NaN  
3           NaN  
4           NaN  
..          ...  
62          NaN  
63          NaN  
64          NaN  
65          NaN  
66          NaN  

[67 rows x 11 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Date                              67 non-null     object 
 1   Day                               67 non-null     object 
 2   Sleep Hour                        67 non-null     int64  
 3   Exercise Hour                     67 non-null     int64  
 4   Study Hour                        67 non-null     int64  
 5   StudyDS Hour                      67 non-null     int64  
 6   Work Hour                         67 non-null     int64  
 7   End of the day Feeling (0 to 10)  67 non-null     int64  
 8   Unnamed: 8                        0 non-null      float64
 9   Unnamed: 9                        0 non-null      float64
 10  Unnamed: 10                       0 non-null      float64
dtypes: float64(3), int64(6), object(2)
memory usage: 5.9+ KB


In [4]:
data.drop(['Unnamed: 8','Unnamed: 9','Unnamed: 10'],axis=1, inplace=True)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 8 columns):
 #   Column                            Non-Null Count  Dtype 
---  ------                            --------------  ----- 
 0   Date                              67 non-null     object
 1   Day                               67 non-null     object
 2   Sleep Hour                        67 non-null     int64 
 3   Exercise Hour                     67 non-null     int64 
 4   Study Hour                        67 non-null     int64 
 5   StudyDS Hour                      67 non-null     int64 
 6   Work Hour                         67 non-null     int64 
 7   End of the day Feeling (0 to 10)  67 non-null     int64 
dtypes: int64(6), object(2)
memory usage: 4.3+ KB


In [6]:
data

Date       Day  Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  \
0   14-Jan    Friday           7              2           2             0   
1   15-Jan  Saturday           7              2           0             0   
2   16-Jan    Sunday           7              0           4             0   
3   17-Jan    Monday           8              4           2             0   
4   18-Jan   Tuesday           8              2           1             0   
..     ...       ...         ...            ...         ...           ...   
62  17-Mar  Thursday           8              0           0             0   
63  18-Mar    Friday           8              2           2             0   
64  19-Mar  Saturday           7              2           0             0   
65  20-Mar    Sunday           7              2           0             0   
66  21-Mar    Monday           8              2           0             0   

    Work Hour  End of the day Feeling (0 to 10)  
0           0                                 1  
1           0                                 2  
2           0                                 1  
3           0                                 1  
4           0                                 1  
..        ...                               ...  
62          2                                 2  
63          1                                 1  
64          2                                 2  
65          0                                 0  
66          0                                 0  

[67 rows x 8 columns]

In [7]:
data.isnull().sum()

Date                                0
Day                                 0
Sleep Hour                          0
Exercise Hour                       0
Study Hour                          0
StudyDS Hour                        0
Work Hour                           0
End of the day Feeling (0 to 10)    0
dtype: int64

In [8]:
X=data[['Day','Sleep Hour','Exercise Hour', 'Study Hour', 'StudyDS Hour', 'Work Hour']]
y=data[['End of the day Feeling (0 to 10)']]

In [9]:
X.head()

Day  Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  Work Hour
0    Friday           7              2           2             0          0
1  Saturday           7              2           0             0          0
2    Sunday           7              0           4             0          0
3    Monday           8              4           2             0          0
4   Tuesday           8              2           1             0          0

In [10]:
y.head()

End of the day Feeling (0 to 10)
0                                 1
1                                 2
2                                 1
3                                 1
4                                 1

In [11]:
X=pd.get_dummies(data[['Day','Sleep Hour','Exercise Hour', 'Study Hour', 'StudyDS Hour', 'Work Hour']],drop_first=False)
X

Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  Work Hour  \
0            7              2           2             0          0   
1            7              2           0             0          0   
2            7              0           4             0          0   
3            8              4           2             0          0   
4            8              2           1             0          0   
..         ...            ...         ...           ...        ...   
62           8              0           0             0          2   
63           8              2           2             0          1   
64           7              2           0             0          2   
65           7              2           0             0          0   
66           8              2           0             0          0   

    Day_Friday  Day_Monday  Day_Saturday  Day_Sunday  Day_Thursday  \
0            1           0             0           0             0   
1            0           0             1           0             0   
2            0           0             0           1             0   
3            0           1             0           0             0   
4            0           0             0           0             0   
..         ...         ...           ...         ...           ...   
62           0           0             0           0             1   
63           1           0             0           0             0   
64           0           0             1           0             0   
65           0           0             0           1             0   
66           0           1             0           0             0   

    Day_Tuesday  Day_Wednesday  
0             0              0  
1             0              0  
2             0              0  
3             0              0  
4             1              0  
..          ...            ...  
62            0              0  
63            0              0  
64            0              0  
65            0              0  
66            0              0  

[67 rows x 12 columns]

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test=train_test_split(X,y, test_size=1/4,random_state=42)

In [13]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [14]:
print('Coefficients',regressor.coef_)

Coefficients [[ 0.04028015  0.08234177  0.03682549  0.00806168  0.19308699 -0.58007903
  -0.40119885 -0.61637555 -0.36091869  0.41643756  0.71400378  0.82813076]]


In [15]:
print('intercept',regressor.intercept_)

intercept [1.09655282]


In [16]:
y_pred=regressor.predict(X_test)

## Tests

In [17]:
#Sunday, 8 hours of sleep, 0 Exercise, 3 Study hours, 0 Ds Study, 3 Work hours
regressor.predict([[8,0,3,0,3,0,0,0,1,0,0,0]])

array([[1.74761284]])

In [18]:
#THursday, 8 hours of sleep, 0 Exercise,2 Study hours, 0 Ds Study, 2 Work hours
regressor.predict([[8,0,2,0,2,0,0,0,0,1,0,0]])

array([[2.2950566]])

In [19]:
#Wednesday, 5 hours of sleep, 4 Exercise,1 Study hours, 1 Ds Study, 0 Work hours
regressor.predict([[5,4,1,1,0,0,0,0,0,0,0,1]])

array([[2.50033859]])

In [20]:
#Monday, 8 hours of sleep, 4 Exercise,2 Study hours, 0 Ds Study, 0 Work hours
regressor.predict([[8,4,2,0,0,0,1,0,0,0,0,0]])

array([[1.42061327]])

In [21]:
#Tuesday, 8 hours of sleep, 2 Exercise,2 Study hours, 2 Ds Study, 0 Work hours
regressor.predict([[8,2,2,2,0,0,0,0,0,0,1,0]])

array([[2.38725572]])

In [24]:
X=sm.add_constant(X)
model=sm.OLS(y,X).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                   OLS Regression Results                                   
============================================================================================
Dep. Variable:     End of the day Feeling (0 to 10)   R-squared:                       0.206
Model:                                          OLS   Adj. R-squared:                  0.048
Method:                               Least Squares   F-statistic:                     1.301
Date:                              Mon, 21 Mar 2022   Prob (F-statistic):              0.249
Time:                                      14:20:36   Log-Likelihood:                -81.775
No. Observations:                                67   AIC:                             187.5
Df Residuals:                                    55   BIC:                             214.0
Df Model:                                        11                                         
Covariance Type:                          nonrobust                                         
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             1.6853      1.096      1.537      0.130      -0.511       3.882
Sleep Hour       -0.0769      0.127     -0.605      0.548      -0.331       0.178
Exercise Hour     0.0837      0.344      0.243      0.809      -0.606       0.774
Study Hour        0.0078      0.116      0.067      0.947      -0.225       0.241
StudyDS Hour      0.0536      0.176      0.304      0.762      -0.299       0.406
Work Hour         0.1293      0.178      0.727      0.470      -0.227       0.486
Day_Friday       -0.1411      0.314     -0.450      0.655      -0.770       0.488
Day_Monday       -0.0538      0.763     -0.070      0.944      -1.583       1.476
Day_Saturday     -0.0602      0.394     -0.153      0.879      -0.850       0.730
Day_Sunday       -0.1307      0.591     -0.221      0.826      -1.314       1.053
Day_Thursday      0.6602      0.678      0.973      0.335      -0.699       2.020
Day_Tuesday       0.7158      0.349      2.050      0.045       0.016       1.415
Day_Wednesday     0.6950      0.824      0.844      0.402      -0.955       2.345
==============================================================================
Omnibus:                       19.508   Durbin-Watson:                   1.730
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               30.933
Skew:                           1.062   Prob(JB):                     1.92e-07
Kurtosis:                       5.563   Cond. No.                     1.17e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.09e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""